=begin
#LaunchDarkly REST API

#Build custom integrations with the LaunchDarkly REST API

OpenAPI spec version: 2.0.0
Contact: support@launchdarkly.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AuditLogApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuditLogApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AuditLogApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuditLogApi' do
    it 'should create an instance of AuditLogApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AuditLogApi)
    end
  end

  # unit tests for get_audit_log_entries
  # Fetch a list of all audit log entries
  # 
  # @param [Hash] opts the optional parameters
  # @return [AuditLogEntries]
  describe 'get_audit_log_entries test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_audit_log_entry
  # Get an audit log entry by ID
  # 
  # @param resource_id The resource ID
  # @param [Hash] opts the optional parameters
  # @return [AuditLogEntry]
  describe 'get_audit_log_entry test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
