=begin
#LaunchDarkly REST API

#Build custom integrations with the LaunchDarkly REST API

OpenAPI spec version: 3.9.0
Contact: support@launchdarkly.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LaunchDarklyApi::FeatureFlagChangeRequestReviewConfigBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FeatureFlagChangeRequestReviewConfigBody' do
  before do
    # run before each test
    @instance = LaunchDarklyApi::FeatureFlagChangeRequestReviewConfigBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FeatureFlagChangeRequestReviewConfigBody' do
    it 'should create an instance of FeatureFlagChangeRequestReviewConfigBody' do
      expect(@instance).to be_instance_of(LaunchDarklyApi::FeatureFlagChangeRequestReviewConfigBody)
    end
  end
  describe 'test attribute "kind"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["approve", "decline"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.kind = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "comment"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
