=begin
#LaunchDarkly REST API

#Build custom integrations with the LaunchDarkly REST API

OpenAPI spec version: 2.0.2
Contact: support@launchdarkly.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Resource
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Resource' do
  before do
    # run before each test
    @instance = SwaggerClient::Resource.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Resource' do
    it 'should create an instance of Resource' do
      expect(@instance).to be_instance_of(SwaggerClient::Resource)
    end
  end
end

