=begin
#LaunchDarkly REST API

#Build custom integrations with the LaunchDarkly REST API

OpenAPI spec version: 2.0.0
Contact: support@launchdarkly.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/audit_log_entries'
require 'swagger_client/models/audit_log_entry'
require 'swagger_client/models/audit_log_entry_target'
require 'swagger_client/models/clause'
require 'swagger_client/models/environment'
require 'swagger_client/models/environment_body'
require 'swagger_client/models/feature_flag'
require 'swagger_client/models/feature_flag_body'
require 'swagger_client/models/feature_flag_config'
require 'swagger_client/models/feature_flag_config_fallthrough'
require 'swagger_client/models/feature_flag_status'
require 'swagger_client/models/feature_flag_statuses'
require 'swagger_client/models/feature_flags'
require 'swagger_client/models/link'
require 'swagger_client/models/links'
require 'swagger_client/models/member'
require 'swagger_client/models/patch_delta'
require 'swagger_client/models/project'
require 'swagger_client/models/project_body'
require 'swagger_client/models/projects'
require 'swagger_client/models/rollout'
require 'swagger_client/models/rule'
require 'swagger_client/models/target'
require 'swagger_client/models/user'
require 'swagger_client/models/user_flag_setting'
require 'swagger_client/models/user_flag_settings'
require 'swagger_client/models/user_settings_body'
require 'swagger_client/models/users'
require 'swagger_client/models/variation'
require 'swagger_client/models/webhook'
require 'swagger_client/models/webhook_body'
require 'swagger_client/models/webhooks'
require 'swagger_client/models/weighted_variation'

# APIs
require 'swagger_client/api/audit_log_api'
require 'swagger_client/api/environments_api'
require 'swagger_client/api/flags_api'
require 'swagger_client/api/projects_api'
require 'swagger_client/api/root_api'
require 'swagger_client/api/user_settings_api'
require 'swagger_client/api/users_api'
require 'swagger_client/api/webhooks_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
