=begin
#LaunchDarkly REST API

#Build custom integrations with the LaunchDarkly REST API

OpenAPI spec version: 4.0.0
Contact: support@launchdarkly.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'date'

module LaunchDarklyApi
  class FeatureFlagApprovalRequestReviewStatus
    
    PENDING = 'pending'.freeze
    APPROVED = 'approved'.freeze
    DECLINED = 'declined'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = FeatureFlagApprovalRequestReviewStatus.constants.select { |c| FeatureFlagApprovalRequestReviewStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #FeatureFlagApprovalRequestReviewStatus" if constantValues.empty?
      value
    end
  end
end
